version: "3.8"

services:
  target-nginx:
    build:
      context: ./Targeted
      dockerfile: nginx
    image: targeted_nginx
    container_name: target-nginx
    networks:
      - elk_net
    ports:
      - "80:80"
    depends_on:
      - attacker-kali-novnc

  target-httpd:
    build:
      context: ./Targeted
      dockerfile: httpd
    image: targeted_httpd
    container_name: target-httpd
    networks:
      - elk_net
    ports:
      - "8081:80"
    depends_on:
      - attacker-kali-novnc

  attacker-kali-novnc:
    build:
      context: ./Attacker
      dockerfile: kali-novnc
    image: attacker_kali-novnc
    container_name: attacker-kali-novnc
    networks:
      - elk_net
    ports:
      - "22:22"
      - "5901:5901"
      - "8080:8080"
    privileged: true
    cap_add:
      - net_admin
    tmpfs:
      - /run
      - /tmp
    security_opt:
      - label:disable
    volumes:
      - /dev/net:/dev/net:z
      - ./data:/data

  attacker-kali-xrdp:
    build:
      context: ./Attacker
      dockerfile: kali-xrdp
    image: attacker_kali-xrdp
    container_name: attacker-kali-xrdp
    networks:
      - elk_net
    ports:
      - "3390:3389"
      - "222:22"
    privileged: true
    cap_add:
      - net_admin
    tmpfs:
      - /run
      - /tmp
    security_opt:
      - label:disable
    volumes:
      - /dev/net:/dev/net:z
      - ./data:/data

  attacker-kali-x11:
    build:
      context: ./Attacker
      dockerfile: kali-x11
    image: attacker_kali-x11
    container_name: attacker-kali-x11
    networks:
      - elk_net
    ports:
      - "223:22"
    privileged: true
    cap_add:
      - net_admin
    tmpfs:
      - /run
      - /tmp
    security_opt:
      - label:disable
    volumes:
      - /dev/net:/dev/net:z
      - ./data:/data

networks:
  elk_net:
    name: elk_net
    driver: bridge
    external: true
