version: "2.2"

services:
  targeted-1:
    image: targeted_nginx
    depends_on:
      - attacker-1
    container_name: targeted-1
    networks:
      - elk_net
    ports:
      - "80:80"

  attacker-1:
    image: attacker_kali-novnc
    container_name: attacker-1
    networks:
      - elk_net
    ports:
      - "22:22"
      - "3389:3389"
      - "5901:5901"
      - "8080:8080"

networks:
  elk_net:
    external: true
