version: '3.5'

services:
  #targeted start
  Targeted-1:
    image: 'httpd'
    container_name: Targeted-1
    tty: true
    stdin_open: true
    #command: bash
    restart: always
    networks:
      - Cnet
      - docker-elk_elk
    ports:
      - "801:80"
  #targeted end
  #attacker start
  Attacker-1:
    image: 'kali-xrdp'
    container_name: Attacker-1
    tty: true
    stdin_open: true
    #command: bash
    privileged: true
    restart: always
    cap_add:
      - net_admin
    tmpfs:
      - /run
      - /tmp
    security_opt:
      - label:disable
    ports:
      - "3389:3389"
      - "222:22"
    working_dir: /
    volumes:
      - /dev/net:/dev/net:z
      - ./data:/data
    networks:
      - Cnet
  #attacker start

networks:
  Cnet:
    driver: bridge
  docker-elk_elk:
    external: true
